Init container does not modify
The necessary tools, users and groups shall be provided by image and/or
ignition.

diff --git a/config/manager/manager.yaml b/config/manager/manager.yaml
--- a/config/manager/manager.yaml
+++ b/config/manager/manager.yaml
@@ -40,10 +40,10 @@ spec:
               value: "65532"
             - name: LIBVIRT_PROVIDER_DIR
               value: "/var/lib/libvirt-provider"
-            - name: LIBVIR_GROUP
-              value: "libvirt"
+            - name: LIBVIRT_GROUP
+              value: "libvirt-qemu"
             - name: DEPENDENCIES
-              value: "ceph-common libvirt-clients"
+              value: "libvirt-daemon-system libvirt-clients ovmf ceph-common"
           args:
             - |
               IFS=' ' read -r -a dependencies <<< "$DEPENDENCIES"
@@ -53,18 +53,22 @@ spec:
                   exit 1
                 fi
               done
-              if ! getent group $(LIBVIR_GROUP); then
-                   echo "Error: $(LIBVIR_GROUP) group does not exist."
-                   exit 1
+              if ! getent group $(LIBVIRT_GROUP); then
+                  echo "Error: $(LIBVIRT_GROUP) group does not exist."
+                  exit 1
               fi
               if ! getent group $(USER_GROUP); then
-                  groupadd -g $(USER_GROUP_ID) $(USER_GROUP)
+                  echo "Error: $(LIBVIRT_GROUP) group does not exist."
+                  exit 1
               fi
               if ! id -u $(USER); then
-                  useradd --no-create-home -g $(USER_GROUP) --uid $(USER_ID) $(USER)
+                  echo "Error: $(USER) user does not exist."
+                  exit 1
               fi
-              usermod -a -G $(LIBVIR_GROUP) $(USER)
-              chown $(USER):$(USER_GROUP) -R $(LIBVIRT_PROVIDER_DIR)
+              if [ ! -d "$(LIBVIRT_PROVIDER_DIR)" ]; then
+                  echo "Error: $(LIBVIRT_PROVIDER_DIR) directory does not exist."
+                  exit 1
+              fi
           volumeMounts:
             - name: etc
               mountPath: /etc
